# this holds the directories of all the functions for the ABM
# Set working directory, import packages, source functions
library(tidyverse)
library(RColorBrewer)
library(cowplot)

setwd(paste0(base.directory, "/source/"))
source(paste0(getwd(), "/lake.location.R"))
source(paste0(getwd(), "/parameters.R"))
source(paste0(getwd(), "/angler.characteristics.R"))
source(paste0(getwd(),"/lake.distance.R"))
source(paste0(getwd(),"/lake.characteristics.R"))
source(paste0(getwd(),"/create.blank.angler.decisions.R"))
source(paste0(getwd(),"/angler.decisions.R"))
source(paste0(getwd(),"/fishing.R"))
source(paste0(getwd(), "/initialize.output.lakes.R"))
source(paste0(getwd(),"/output.script.R"))
source(paste0(getwd(),"/plotting.lake.status.R"))
source(paste0(getwd(), "/initialize.annual.exploitation.R"))
source(paste0(getwd(),"/annual.exploitation.R"))